POST http://localhost:3000/api/token/test/generate HTTP/1.1
Content-Type: application/json

{
  "roles": [0],
  "username": "some-name"
}

###

POST http://localhost:3000/api/token/validate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6Ijo6ZmZmZjoxMjcuMC4wLjEiLCJyb2xlcyI6WzBdLCJ1c2VybmFtZSI6InNvbWUtbmFtZSIsImlhdCI6MTU4OTI0OTcxNSwiZXhwIjoxNTg5MjUzMzE1fQ.OTaGge6pMLnfCklT4LNWkJJy7trmmi1rnGcXkkhcYus
