POST http://localhost:3000/api/token/test/generate HTTP/1.1
Content-Type: application/json

{
  "ip": "some-ip",
  "roles": [0],
  "username": "some-name"
}

###

POST http://localhost:3000/api/token/validate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6InNvbWUtaXAiLCJyb2xlX2xldmVsIjowLCJ1c2VybmFtZSI6InNvbWUtbmFtZSIsImlhdCI6MTU4ODkzMTM0NSwiZXhwIjoxNTg4OTM0OTQ1fQ.BtK84zoElam_nVRNGqGXpGnCIHiI7OzwgBTeNfPww1s
